services:
  redis-queue:
    container_name: novelty-redis-queue
    image: redis
    restart: always
    ports:
      - "6380:6380"
    volumes:
      - redis-queue-data:/data
    entrypoint: redis-server --port 6380 --appendonly yes


volumes:
  redis-queue-data:
