/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as legalTermsOfServiceRouteImport } from "./routes/(legal)/terms-of-service";
import { Route as authVerifyEmailRouteImport } from "./routes/(auth)/verify-email";
import { Route as authRegisterRouteImport } from "./routes/(auth)/register";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const legalTermsOfServiceRoute = legalTermsOfServiceRouteImport.update({
  id: "/(legal)/terms-of-service",
  path: "/terms-of-service",
  getParentRoute: () => rootRouteImport,
} as any);
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: "/(auth)/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any);
const authRegisterRoute = authRegisterRouteImport.update({
  id: "/(auth)/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/register": typeof authRegisterRoute;
  "/verify-email": typeof authVerifyEmailRoute;
  "/terms-of-service": typeof legalTermsOfServiceRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/register": typeof authRegisterRoute;
  "/verify-email": typeof authVerifyEmailRoute;
  "/terms-of-service": typeof legalTermsOfServiceRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/(auth)/register": typeof authRegisterRoute;
  "/(auth)/verify-email": typeof authVerifyEmailRoute;
  "/(legal)/terms-of-service": typeof legalTermsOfServiceRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/register" | "/verify-email" | "/terms-of-service";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/register" | "/verify-email" | "/terms-of-service";
  id:
    | "__root__"
    | "/"
    | "/(auth)/register"
    | "/(auth)/verify-email"
    | "/(legal)/terms-of-service";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  authRegisterRoute: typeof authRegisterRoute;
  authVerifyEmailRoute: typeof authVerifyEmailRoute;
  legalTermsOfServiceRoute: typeof legalTermsOfServiceRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(legal)/terms-of-service": {
      id: "/(legal)/terms-of-service";
      path: "/terms-of-service";
      fullPath: "/terms-of-service";
      preLoaderRoute: typeof legalTermsOfServiceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/verify-email": {
      id: "/(auth)/verify-email";
      path: "/verify-email";
      fullPath: "/verify-email";
      preLoaderRoute: typeof authVerifyEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)/register": {
      id: "/(auth)/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof authRegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRegisterRoute: authRegisterRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  legalTermsOfServiceRoute: legalTermsOfServiceRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
