/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthRouteRouteImport } from "./routes/_auth/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthVerifyEmailRouteImport } from "./routes/_auth/verify-email";
import { Route as AuthRegisterRouteImport } from "./routes/_auth/register";
import { Route as AuthLoginRouteImport } from "./routes/_auth/login";
import { Route as userOnboardingRouteImport } from "./routes/(user)/onboarding";
import { Route as legalTermsOfServiceRouteImport } from "./routes/(legal)/terms-of-service";

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AuthRouteRoute,
} as any);
const userOnboardingRoute = userOnboardingRouteImport.update({
  id: "/(user)/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const legalTermsOfServiceRoute = legalTermsOfServiceRouteImport.update({
  id: "/(legal)/terms-of-service",
  path: "/terms-of-service",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/terms-of-service": typeof legalTermsOfServiceRoute;
  "/onboarding": typeof userOnboardingRoute;
  "/login": typeof AuthLoginRoute;
  "/register": typeof AuthRegisterRoute;
  "/verify-email": typeof AuthVerifyEmailRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/terms-of-service": typeof legalTermsOfServiceRoute;
  "/onboarding": typeof userOnboardingRoute;
  "/login": typeof AuthLoginRoute;
  "/register": typeof AuthRegisterRoute;
  "/verify-email": typeof AuthVerifyEmailRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteRouteWithChildren;
  "/(legal)/terms-of-service": typeof legalTermsOfServiceRoute;
  "/(user)/onboarding": typeof userOnboardingRoute;
  "/_auth/login": typeof AuthLoginRoute;
  "/_auth/register": typeof AuthRegisterRoute;
  "/_auth/verify-email": typeof AuthVerifyEmailRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/terms-of-service"
    | "/onboarding"
    | "/login"
    | "/register"
    | "/verify-email";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/terms-of-service"
    | "/onboarding"
    | "/login"
    | "/register"
    | "/verify-email";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/(legal)/terms-of-service"
    | "/(user)/onboarding"
    | "/_auth/login"
    | "/_auth/register"
    | "/_auth/verify-email";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  legalTermsOfServiceRoute: typeof legalTermsOfServiceRoute;
  userOnboardingRoute: typeof userOnboardingRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/verify-email": {
      id: "/_auth/verify-email";
      path: "/verify-email";
      fullPath: "/verify-email";
      preLoaderRoute: typeof AuthVerifyEmailRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/register": {
      id: "/_auth/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/login": {
      id: "/_auth/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/(user)/onboarding": {
      id: "/(user)/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof userOnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(legal)/terms-of-service": {
      id: "/(legal)/terms-of-service";
      path: "/terms-of-service";
      fullPath: "/terms-of-service";
      preLoaderRoute: typeof legalTermsOfServiceRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  legalTermsOfServiceRoute: legalTermsOfServiceRoute,
  userOnboardingRoute: userOnboardingRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
