export const DEFAULT_AVATAR_URL =
  "https://pub-f2576f433d854257870dd0280684809a.r2.dev/profile_pictures/default-avatar-512.webp" as const;

export const MAX_RESULTS_BASIC_SEARCH = 5 as const;

export const BOOK_GENRES_STATIC = [
  // FICTION
  "Literary Fiction",
  "Historical Fiction",
  "Contemporary Fiction",
  "Coming-of-Age",
  "Family Saga",
  "Adventure",
  "Action & Adventure",
  "Western",
  "War Fiction",
  "Satire",
  "Humor",
  "Short Stories",
  "Novella",
  "Anthology",
  "Graphic Novel",
  "Manga",
  "Drama",
  "Poetry",

  // Speculative
  "Fantasy",
  "High Fantasy",
  "Epic Fantasy",
  "Urban Fantasy",
  "Dark Fantasy",
  "Sword & Sorcery",
  "Science Fiction",
  "Hard Science Fiction",
  "Space Opera",
  "Cyberpunk",
  "Steampunk",
  "Dystopian",
  "Post-Apocalyptic",
  "Time Travel",
  "Alternate History",
  "Magical Realism",

  // Mystery / Thriller / Crime
  "Mystery",
  "Detective",
  "Cozy Mystery",
  "Police Procedural",
  "Noir",
  "Crime Fiction",
  "Thriller",
  "Psychological Thriller",
  "Legal Thriller",
  "Techno-Thriller",
  "Domestic Thriller",
  "Espionage",

  // Horror / Supernatural
  "Horror",
  "Gothic Horror",
  "Paranormal",
  "Supernatural",

  // Romance
  "Romance",
  "Contemporary Romance",
  "Historical Romance",
  "Romantic Suspense",
  "Paranormal Romance",
  "Romantic Comedy",

  // Age categories
  "Young Adult (YA)",
  "New Adult",
  "Middle Grade",
  "Children's",

  // Non-Fiction
  "Biography",
  "Autobiography",
  "Memoir",
  "True Crime",
  "History",
  "Politics",
  "Current Affairs",
  "Philosophy",
  "Psychology",
  "Science",
  "Popular Science",
  "Technology",
  "Business",
  "Economics",
  "Finance & Investing",
  "Self-Help",
  "Personal Development",
  "Health & Wellness",
  "Fitness",
  "Nutrition",
  "Cooking",
  "Food & Drink",
  "Travel",
  "Art",
  "Photography",
  "Music",
  "Film & TV",
  "Sports",
  "Religion",
  "Spirituality",
  "Nature",
  "Environment",
  "Gardening",
  "Crafts & Hobbies",
  "Education",
  "Essays",
] as const;

export const BOOK_AUTHORS: string[] = [
  // Classics & Literary
  "William Shakespeare",
  "Jane Austen",
  "Charles Dickens",
  "Mark Twain",
  "Leo Tolstoy",
  "Fyodor Dostoevsky",
  "Victor Hugo",
  "Gustave Flaubert",
  "Homer",
  "Dante Alighieri",
  "Geoffrey Chaucer",
  "Miguel de Cervantes",
  "Herman Melville",
  "Emily Brontë",
  "Charlotte Brontë",
  "Mary Shelley",
  "Bram Stoker",
  "Oscar Wilde",
  "Virginia Woolf",
  "James Joyce",
  "Franz Kafka",
  "Marcel Proust",
  "Anton Chekhov",
  "Nikolai Gogol",
  "George Eliot",
  "Thomas Hardy",
  "Henry James",
  "Joseph Conrad",
  "Edith Wharton",
  "John Steinbeck",
  "Ernest Hemingway",
  "F. Scott Fitzgerald",
  "D. H. Lawrence",
  "Sylvia Plath",
  "Toni Morrison",
  "Ralph Ellison",
  "Zora Neale Hurston",
  "Langston Hughes",
  "Albert Camus",
  "Jean-Paul Sartre",
  "Simone de Beauvoir",
  "Marguerite Duras",
  "Haruki Murakami",
  "Kazuo Ishiguro",
  "Salman Rushdie",
  "Arundhati Roy",
  "Jhumpa Lahiri",
  "Amitav Ghosh",
  "Khaled Hosseini",
  "Elena Ferrante",
  "Umberto Eco",
  "Italo Calvino",
  "Milan Kundera",
  "Elif Shafak",
  "Orhan Pamuk",
  "Karl Ove Knausgård",
  "Naguib Mahfouz",
  "Hisham Matar",
  "Chinua Achebe",
  "Wole Soyinka",
  "Ngũgĩ wa Thiong'o",
  "Nadine Gordimer",
  "J. M. Coetzee",
  "Nnedi Okorafor",
  "Han Kang",
  "Min Jin Lee",
  "Yasunari Kawabata",
  "Yukio Mishima",
  "Banana Yoshimoto",
  "Mo Yan",
  "Gao Xingjian",
  "Rabindranath Tagore",
  "Aravind Adiga",
  "Kiran Desai",
  "Elif Batuman",
  "Celeste Ng",
  "Colson Whitehead",
  "George Saunders",
  "Donna Tartt",

  // Speculative (SFF)
  "J. R. R. Tolkien",
  "C. S. Lewis",
  "George R. R. Martin",
  "J. K. Rowling",
  "Ursula K. Le Guin",
  "Octavia E. Butler",
  "Isaac Asimov",
  "Arthur C. Clarke",
  "Philip K. Dick",
  "Robert A. Heinlein",
  "Frank Herbert",
  "Neil Gaiman",
  "Terry Pratchett",
  "Brandon Sanderson",
  "Patrick Rothfuss",
  "N. K. Jemisin",
  "Ken Liu",
  "Liu Cixin",
  "Ann Leckie",
  "Becky Chambers",
  "Andrzej Sapkowski",
  "Leigh Bardugo",
  "Naomi Novik",
  "V. E. Schwab",
  "Susanna Clarke",
  "Tamsyn Muir",
  "R. F. Kuang",
  "Holly Black",
  "Madeline Miller",
  "Neal Stephenson",
  "Kim Stanley Robinson",
  "Iain M. Banks",
  "China Miéville",
  "Gene Wolfe",
  "Lois Lowry",
  "Madeleine L'Engle",
  "Philip Pullman",
  "Rick Riordan",
  "Sarah J. Maas",
  "Cassandra Clare",
  "Stephenie Meyer",
  "Suzanne Collins",
  "Veronica Roth",
  "Tahereh Mafi",

  // Mystery / Thriller / Crime
  "Agatha Christie",
  "Arthur Conan Doyle",
  "Dashiell Hammett",
  "Raymond Chandler",
  "Dorothy L. Sayers",
  "P. D. James",
  "Ruth Rendell",
  "Patricia Highsmith",
  "Gillian Flynn",
  "Tana French",
  "Michael Connelly",
  "Lee Child",
  "James Patterson",
  "Dan Brown",
  "Stieg Larsson",
  "Jo Nesbø",
  "Henning Mankell",
  "Karin Slaughter",
  "Harlan Coben",
  "Paula Hawkins",
  "Louise Penny",

  // Horror / Supernatural
  "Stephen King",
  "Shirley Jackson",
  "Clive Barker",
  "H. P. Lovecraft",
  "Anne Rice",
  "Dean Koontz",
  "Josh Malerman",

  // Romance & Book Club
  "Nicholas Sparks",
  "Nora Roberts",
  "Colleen Hoover",
  "Julia Quinn",
  "Sarah MacLean",
  "Tessa Dare",
  "Christina Lauren",
  "Ali Hazelwood",
  "Emily Henry",

  // YA & Contemporary
  "John Green",
  "Rainbow Rowell",
  "Angie Thomas",

  // Non-fiction / Memoir
  "Malcolm Gladwell",
  "Michael Lewis",
  "Yuval Noah Harari",
  "David Grann",
  "Erik Larson",
  "Walter Isaacson",
  "Atul Gawande",
  "Mary Roach",
  "Jon Krakauer",
  "Oliver Sacks",
  "Bessel van der Kolk",
  "Joan Didion",
  "Roxane Gay",
  "Ta-Nehisi Coates",
  "Michelle Obama",
  "Barack Obama",
] as const;

export const BOOK_SERIES: string[] = [
  // Epic / High Fantasy
  "The Lord of the Rings",
  "A Song of Ice and Fire",
  "The Wheel of Time",
  "The Stormlight Archive",
  "Mistborn",
  "The Witcher",
  "Malazan Book of the Fallen",
  "The First Law",
  "The Riftwar Cycle",
  "The Realm of the Elderlings",
  "The Farseer Trilogy",
  "The Liveship Traders",
  "The Tawny Man Trilogy",
  "Fitz and the Fool",
  "Memory, Sorrow, and Thorn",
  "The Belgariad",
  "The Malloreon",
  "The Chronicles of Prydain",
  "Earthsea Cycle",
  "The Dark Tower",
  "Discworld",
  "The Chronicles of Narnia",
  "His Dark Materials",
  "The Kingkiller Chronicle",
  "Temeraire",
  "The Old Kingdom (Abhorsen)",
  "The Riyria Revelations",
  "The Riyria Chronicles",
  "The Long Price Quartet",
  "The Dagger and the Coin",
  "The Broken Empire",
  "The Red Queen's War",
  "The Shattered Sea",
  "The Faithful and the Fallen",
  "Of Blood and Bone",
  "Lightbringer",
  "The Licanius Trilogy",
  "The Powder Mage Trilogy",
  "Gods of Blood and Powder",
  "The Books of Babel",
  "The Black Company",
  "The Divine Cities",
  "The Daevabad Trilogy",
  "The Green Bone Saga",
  "The Poppy War Trilogy",
  "The Broken Earth Trilogy",

  // Urban Fantasy / Paranormal
  "The Dresden Files",
  "Rivers of London",
  "Mercy Thompson",
  "Kate Daniels",
  "October Daye",
  "The Hollows",
  "Anita Blake: Vampire Hunter",
  "The Iron Druid Chronicles",
  "The Southern Vampire Mysteries (Sookie Stackhouse)",

  // YA / New Adult Fantasy
  "Throne of Glass",
  "A Court of Thorns and Roses",
  "The Folk of the Air",
  "The Raven Cycle",
  "Shadow and Bone (The Grisha Trilogy)",
  "Six of Crows (Grishaverse)",
  "The Shadowhunter Chronicles",
  "The Mortal Instruments",
  "The Infernal Devices",
  "The Dark Artifices",
  "The Last Hours",
  "The Inheritance Cycle",
  "The Lunar Chronicles",
  "Artemis Fowl",
  "Skulduggery Pleasant",

  // Dystopian / Adventure YA
  "The Hunger Games",
  "Divergent",
  "The Maze Runner",
  "The Selection",
  "Uglies",
  "Delirium",
  "Chaos Walking",
  "Percy Jackson & the Olympians",
  "The Heroes of Olympus",
  "Magnus Chase and the Gods of Asgard",
  "The Trials of Apollo",

  // Science Fiction
  "Dune",
  "Foundation",
  "Hyperion Cantos",
  "The Culture Series",
  "Revelation Space",
  "Ender's Saga",
  "Vorkosigan Saga",
  "The Commonwealth Saga",
  "Old Man's War",
  "The Expanse",
  "Red Rising Saga",
  "Bobiverse",
  "Remembrance of Earth's Past (Three-Body Problem)",
  "Wayfarers",
  "The Murderbot Diaries",
  "Skyward",
  "Children of Time (Series)",
  "The Southern Reach Trilogy",

  // Mystery / Thriller / Crime
  "Hercule Poirot",
  "Miss Marple",
  "Sherlock Holmes",
  "Cormoran Strike",
  "Millennium (The Girl with the Dragon Tattoo)",
  "Jack Reacher",
  "Harry Bosch",
  "Alex Cross",
  "Chief Inspector Armand Gamache",
  "Inspector Rebus",
  "Inspector Lynley",
  "The No. 1 Ladies' Detective Agency",
  "The Thursday Murder Club",

  // Romance & Historical Romance
  "Bridgerton",
  "The Ravenels",
  "The Wallflowers",
  "Psy-Changeling",
] as const;
