services:
  prometheus:
    network_mode: "bridge"
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
  
  loki:
      network_mode: "bridge"
      ports:
      - "${LOKI_PORT}:${LOKI_PORT}"

  promtail:
    network_mode: "bridge"
    ports:
    - "${PROMTAIL_PORT}:${PROMTAIL_PORT}"

  grafana:
    network_mode: "bridge"
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"

