openapi: 3.0.0
info:
  description: Novelty API
  version: 0.0.1
  title: Novelty API
tags:
  - name: Healthcheck
components:
  schemas: {}
  parameters: {}
paths:
  /healthcheck:
    get:
      tags:
        - Healthcheck
      description: Verifies the status of the API
      responses:
        '200':
          description: Successful healthcheck
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - healthy
                  environment:
                    type: string
                    enum:
                      - development
                      - production
                      - test
                      - debug
                  readiness:
                    type: object
                    properties:
                      database:
                        type: string
                        enum:
                          - connected
                example:
                  status: healthy
                  environment: development
                  readiness:
                    database: connected
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - unhealthy
                  environment:
                    type: string
                    enum:
                      - development
                      - production
                      - test
                      - debug
                  readiness:
                    type: object
                    properties:
                      database:
                        type: string
                        enum:
                          - disconnected
                example:
                  status: unhealthy
                  environment: development
                  readiness:
                    database: disconnected
