
name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:


jobs:
  lint-open-api-spec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["lts/*"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Setup pnpm cache
        id: pnpm-cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install deps (with cache)
        run: pnpm install --shamefully-hoist 

      - name: TurboRepo Remote Cache Server
        uses: trappar/turborepo-remote-cache-gh-action@main
        with:
          storage-provider: s3
          storage-path: novelty-remote-cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}       

      - name: generate open api specification
        run: pnpm turbo open-api:generate

      - name: lint open api specification
        run: pnpm turbo open-api:lint
